// Code generated by go generate; DO NOT EDIT.

package tracer

import (
	"context"
	"sync"
)

var componentName = "gravity-assist.tracer"

type Component struct{}

func NewComponent() *Component {
	return &Component{}
}

func (d *Component) Start(ctx context.Context, wg *sync.WaitGroup) {
	Start(ctx, wg)
}

func (d *Component) Name() string {
	return "tracer"
}
