package consts

const (
	MIMEApplicationJSON = "application/json"
	MIMEApplicationXML  = "application/xml"
	MIMETextXML         = "text/xml"
	MIMEApplicationForm = "application/x-www-form-urlencoded"
	MIMEOctetStream     = "application/octet-stream"
	MIMEMultipartForm   = "multipart/form-data"
	MIMETextPlain       = "text/plain"
	MIMETextHTML        = "text/html"
	MIMETextJavascript  = "text/javascript"
	MIMETextCSS         = "text/css"
	MIMETextCSV         = "text/csv"
	MIMETextCalendar    = "text/calendar"
	MIMEImagePNG        = "image/png"
	MIMEImageJPEG       = "image/jpeg"
	MIMEImageGIF        = "image/gif"
	MIMEImageBMP        = "image/bmp"
	MIMEImageTIFF       = "image/tiff"
	MIMEAudioMPEG       = "audio/mpeg"
	MIMEAudioOGG        = "audio/ogg"
	MIMEAudioWAV        = "audio/wav"
	MIMEVideoMPEG       = "video/mpeg"
	MIMEVideoMP4        = "video/mp4"
	MIMEVideoQuickTime  = "video/quicktime"
	MIMEVideoWMV        = "video/x-ms-wmv"
	MIMEVideoAVI        = "video/x-msvideo"
	MIMEApplicationPDF  = "application/pdf"
	MIMEApplicationZIP  = "application/zip"
	MIMEApplicationGZIP = "application/gzip"
	MIMEApplicationTAR  = "application/tar"
)
